export const UPDATE_USERNAME = "UPDATE_USERNAME";
export const GET_CARDS = "GET_CARDS";
export const TOGGLE_CORRECT_MODAL = "TOGGLE_CORRECT_MODAL";
export const TOGGLE_INCORRECT_MODAL = "TOGGLE_INCORRECT_MODAL";
